// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-verified-claims.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-verified-claims.ts
var search_verified_claims_default = defineTool({
  name: "search_verified_claims",
  title: "Search verified claims",
  description: "Search GAINN's verified news claims by keyword or topic. Returns claim text, status, confidence and topic.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword or phrase to search claim text and topic for."),
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of claims to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const escaped = query.replace(/[%,]/g, " ");
    const { data, error } = await supabase.from("claims").select("id, claim_text, topic, status, confidence, last_seen_at").or(`claim_text.ilike.%${escaped}%,topic.ilike.%${escaped}%`).order("last_seen_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { claims: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-video-reports.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_video_reports_default = defineTool2({
  name: "list_video_reports",
  title: "List AI video reports",
  description: "List GAINN's AI-generated video news reports, newest first, with title, category, duration and narration script.",
  inputSchema: {
    category: z2.string().trim().min(1).optional().describe("Optional category filter, e.g. politics or crime."),
    include_script: z2.boolean().default(false).describe("Include the full narration script for each report."),
    limit: z2.number().int().min(1).max(25).default(10).describe("Maximum number of reports to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, include_script, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("generated_videos").select(
      include_script ? "id, title, category, duration, thumbnail_url, generated_at, script, short_script" : "id, title, category, duration, thumbnail_url, generated_at"
    ).order("generated_at", { ascending: false }).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-saved-articles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_saved_articles_default = defineTool3({
  name: "list_saved_articles",
  title: "List saved articles",
  description: "List the signed-in user's saved GAINN articles, most recently saved first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(20).describe("Maximum number of saved articles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_articles").select("id, article_id, headline, summary, category, region, source_url, published_at, saved_at").eq("user_id", ctx.getUserId()).order("saved_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-article.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var save_article_default = defineTool4({
  name: "save_article",
  title: "Save article",
  description: "Save a news article to the signed-in user's GAINN reading list.",
  inputSchema: {
    article_id: z4.string().trim().min(1).describe("Stable identifier of the article (URL or GAINN article id)."),
    headline: z4.string().trim().min(1).describe("Article headline."),
    summary: z4.string().trim().optional().describe("Short summary of the article."),
    category: z4.string().trim().optional().describe("Article category, e.g. politics."),
    region: z4.string().trim().optional().describe("Region the story belongs to."),
    source_url: z4.string().url().optional().describe("Original source URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_articles").upsert(
      {
        user_id: ctx.getUserId(),
        article_id: input.article_id,
        headline: input.headline,
        summary: input.summary ?? null,
        category: input.category ?? null,
        region: input.region ?? null,
        source_url: input.source_url ?? null
      },
      { onConflict: "user_id,article_id" }
    ).select("id, article_id, headline, saved_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${input.headline}".` }],
      structuredContent: { article: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/remove-saved-article.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var remove_saved_article_default = defineTool5({
  name: "remove_saved_article",
  title: "Remove saved article",
  description: "Remove an article from the signed-in user's GAINN reading list.",
  inputSchema: {
    article_id: z5.string().trim().min(1).describe("Identifier of the saved article to remove.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ article_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("saved_articles").delete().eq("user_id", ctx.getUserId()).eq("article_id", article_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Removed article ${article_id} from the reading list.` }] };
  }
});

// src/lib/mcp/tools/get-news-preferences.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_news_preferences_default = defineTool6({
  name: "get_news_preferences",
  title: "Get news preferences",
  description: "Read the signed-in user's GAINN news preferences (categories and regions).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("news_preferences").select("categories, regions, regional_weights, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { categories: [], regions: [] }, null, 2) }],
      structuredContent: { preferences: data ?? null }
    };
  }
});

// src/lib/mcp/tools/update-news-preferences.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var update_news_preferences_default = defineTool7({
  name: "update_news_preferences",
  title: "Update news preferences",
  description: "Update the signed-in user's GAINN news categories and regions.",
  inputSchema: {
    categories: z6.array(z6.string().trim().min(1)).max(20).optional().describe("Preferred news categories."),
    regions: z6.array(z6.string().trim().min(1)).max(20).optional().describe("Preferred regions, e.g. India, Delhi.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ categories, regions }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!categories && !regions) {
      return { content: [{ type: "text", text: "Provide categories, regions, or both." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const payload = { user_id: ctx.getUserId() };
    if (categories) payload.categories = categories;
    if (regions) payload.regions = regions;
    const { data, error } = await supabase.from("news_preferences").upsert(payload, { onConflict: "user_id" }).select("categories, regions, updated_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}, null, 2) }],
      structuredContent: { preferences: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lwdzzvrzsrssaocaprnl";
var mcp_default = defineMcp({
  name: "global-ai-news",
  title: "Global AI News",
  version: "0.1.0",
  instructions: "Tools for GAINN, an autonomous AI news agency. Search verified news claims, browse AI-generated video reports, and manage the signed-in user's saved articles and news preferences.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_verified_claims_default,
    list_video_reports_default,
    list_saved_articles_default,
    save_article_default,
    remove_saved_article_default,
    get_news_preferences_default,
    update_news_preferences_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
